import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const connectionString = process.env.DATABASE_URL!
const adapter = new PrismaPg({ connectionString })
const prisma = new PrismaClient({ adapter } as any)

const seedData = [
  {
    exactBusinessName: 'Rasa Fine Dining',
    status: 'ACTIVE' as const,
    businessType: 'Fine Dining Restaurant',
    category: 'Restaurant',
    neighbourhood: 'Jubilee Hills',
    revenueRangeMin: 700000,
    revenueRangeMax: 900000,
    askingPriceRangeMin: 15000000,
    askingPriceRangeMax: 18000000,
    yearsInOperation: 7,
    sqftRange: '3,800–4,200 sq ft',
    tags: ['Fully Operational', 'Prime Location', 'Liquor License', '80 Covers'],
    highlights: [
      'Established clientele with 7 years of consistent footfall',
      'Full bar setup with valid liquor license',
      'Lease balance of 6 years remaining',
      'Monthly revenue ₹7L–9L with 18% profit margin',
    ],
    heroImage: '/images/fine-dining-restaurant.jpg',
    publicImages: ['/images/fine-dining-restaurant.jpg'],
    fullAddress: 'Plot 42, Road No. 36, Jubilee Hills, Hyderabad - 500033',
    ownerName: 'Suresh Reddy',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'suresh@rasadining.com',
    exactMonthlyRevenue: 820000,
    exactAskingPrice: 16500000,
    leaseYears: 6,
    profitMargin: 18,
    additionalNotes: 'Owner relocating abroad. Serious buyers only.',
    fullGallery: ['/images/fine-dining-restaurant.jpg'],
  },
  {
    exactBusinessName: 'The Copper Kettle',
    status: 'ACTIVE' as const,
    businessType: 'Artisan Cafe & Bakery',
    category: 'Cafe',
    neighbourhood: 'Banjara Hills',
    revenueRangeMin: 400000,
    revenueRangeMax: 550000,
    askingPriceRangeMin: 6000000,
    askingPriceRangeMax: 8000000,
    yearsInOperation: 4,
    sqftRange: '1,400–1,600 sq ft',
    tags: ['Profitable', 'Loyal Customer Base', 'Fully Equipped', 'Instagram Famous'],
    highlights: [
      'Strong social media presence with 28K followers',
      'In-house bakery with signature recipes',
      'Lease balance of 4 years remaining',
      'Average daily footfall of 120–150 customers',
    ],
    heroImage: '/images/cafe-banjara.png',
    publicImages: ['/images/cafe-banjara.png'],
    fullAddress: '8-2-293/82/A, Road No. 14, Banjara Hills, Hyderabad - 500034',
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 91234 56789',
    ownerEmail: 'priya@copperkettlecafe.com',
    exactMonthlyRevenue: 480000,
    exactAskingPrice: 7200000,
    leaseYears: 4,
    profitMargin: 22,
    additionalNotes: 'Owner expanding to a new concept. Full handover support offered.',
    fullGallery: ['/images/cafe-banjara.png'],
  },
  {
    exactBusinessName: 'Skyline 360',
    status: 'ACTIVE' as const,
    businessType: 'Rooftop Restaurant',
    category: 'Restaurant',
    neighbourhood: 'Banjara Hills',
    revenueRangeMin: 900000,
    revenueRangeMax: 1200000,
    askingPriceRangeMin: 20000000,
    askingPriceRangeMax: 25000000,
    yearsInOperation: 5,
    sqftRange: '4,500–5,000 sq ft',
    tags: ['Rooftop', 'City View', 'Liquor License', '120 Covers'],
    highlights: [
      'Panoramic views of Hyderabad city skyline',
      'Valid liquor license with bar setup',
      'Average weekend covers: 200+',
      'Monthly revenue ₹9L–12L with 21% profit margin',
    ],
    heroImage: '/images/restaurant-rooftop.png',
    publicImages: ['/images/restaurant-rooftop.png'],
    fullAddress: 'Level 12, Road No. 12, Banjara Hills, Hyderabad - 500034',
    ownerName: 'Vikram Nair',
    ownerPhone: '+91 98765 11111',
    ownerEmail: 'vikram@skyline360.com',
    exactMonthlyRevenue: 1050000,
    exactAskingPrice: 22000000,
    leaseYears: 5,
    profitMargin: 21,
    additionalNotes: 'Owner opening second property in Bengaluru. Full team stays on.',
    fullGallery: ['/images/restaurant-rooftop.png'],
  },
  {
    exactBusinessName: 'Blank Page Cafe',
    status: 'ACTIVE' as const,
    businessType: 'Minimalist Specialty Cafe',
    category: 'Cafe',
    neighbourhood: 'Madhapur',
    revenueRangeMin: 300000,
    revenueRangeMax: 450000,
    askingPriceRangeMin: 4500000,
    askingPriceRangeMax: 6000000,
    yearsInOperation: 3,
    sqftRange: '900–1,100 sq ft',
    tags: ['Specialty Coffee', 'Minimal Design', 'High Footfall', 'HITEC City'],
    highlights: [
      'Located 2 mins from HITEC City tech hub',
      'Loyal weekday corporate clientele',
      'Specialty single-origin coffee program',
      'Average daily revenue ₹12,000–15,000',
    ],
    heroImage: '/images/cafe-minimalist.png',
    publicImages: ['/images/cafe-minimalist.png'],
    fullAddress: 'Plot 18, Cyber Pearl, HITEC City, Hyderabad - 500081',
    ownerName: 'Arjun Mehta',
    ownerPhone: '+91 91234 22222',
    ownerEmail: 'arjun@blankpagecafe.com',
    exactMonthlyRevenue: 380000,
    exactAskingPrice: 5200000,
    leaseYears: 3,
    profitMargin: 24,
    additionalNotes: 'Owner relocating to Singapore. Immediate handover available.',
    fullGallery: ['/images/cafe-minimalist.png'],
  },
  {
    exactBusinessName: 'The Verdant House',
    status: 'ACTIVE' as const,
    businessType: 'Greenhouse Garden Cafe',
    category: 'Cafe',
    neighbourhood: 'Jubilee Hills',
    revenueRangeMin: 500000,
    revenueRangeMax: 700000,
    askingPriceRangeMin: 8000000,
    askingPriceRangeMax: 10000000,
    yearsInOperation: 4,
    sqftRange: '2,800–3,200 sq ft',
    tags: ['Garden Dining', 'Instagram Famous', 'Weekend Hotspot', 'Fully Operational'],
    highlights: [
      'Over 45K Instagram followers, zero paid marketing',
      'Weekend waiting list of 2–3 hours',
      'Unique greenhouse concept — only one in Hyderabad',
      'Monthly revenue ₹5L–7L with 19% margin',
    ],
    heroImage: '/images/cafe-greenhouse.png',
    publicImages: ['/images/cafe-greenhouse.png'],
    fullAddress: 'Plot 8, Road No. 45, Jubilee Hills, Hyderabad - 500033',
    ownerName: 'Sneha Reddy',
    ownerPhone: '+91 98765 33333',
    ownerEmail: 'sneha@verdanthouse.in',
    exactMonthlyRevenue: 600000,
    exactAskingPrice: 9000000,
    leaseYears: 5,
    profitMargin: 19,
    additionalNotes: 'Full brand, social media handles, and recipes included in sale.',
    fullGallery: ['/images/cafe-greenhouse.png'],
  },
  {
    exactBusinessName: 'La Petite Patisserie',
    status: 'ACTIVE' as const,
    businessType: 'French Patisserie & Dessert Cafe',
    category: 'Cafe',
    neighbourhood: 'Film Nagar',
    revenueRangeMin: 400000,
    revenueRangeMax: 600000,
    askingPriceRangeMin: 7000000,
    askingPriceRangeMax: 9000000,
    yearsInOperation: 3,
    sqftRange: '1,600–1,800 sq ft',
    tags: ['Premium Desserts', 'High Margin', 'Loyal Clientele', 'Unique Concept'],
    highlights: [
      'Only French patisserie concept in Film Nagar',
      'Average ticket size ₹800 — highest in category',
      'Celebrity and influencer clientele',
      'Proprietary macaron and pastry recipes included',
    ],
    heroImage: '/images/cafe-dessert.png',
    publicImages: ['/images/cafe-dessert.png'],
    fullAddress: 'Plot 22, Film Nagar, Jubilee Hills, Hyderabad - 500096',
    ownerName: 'Meera Kapoor',
    ownerPhone: '+91 91234 44444',
    ownerEmail: 'meera@lapetitepatisserie.in',
    exactMonthlyRevenue: 500000,
    exactAskingPrice: 8000000,
    leaseYears: 4,
    profitMargin: 28,
    additionalNotes: 'Chef-owner willing to train new owner for 3 months post-sale.',
    fullGallery: ['/images/cafe-dessert.png'],
  },
  {
    exactBusinessName: "Nawab's Darbar",
    status: 'ACTIVE' as const,
    businessType: 'Heritage Fine Dining',
    category: 'Restaurant',
    neighbourhood: 'Old City',
    revenueRangeMin: 1200000,
    revenueRangeMax: 1800000,
    askingPriceRangeMin: 35000000,
    askingPriceRangeMax: 45000000,
    yearsInOperation: 12,
    sqftRange: '6,000–7,000 sq ft',
    tags: ['Heritage Property', 'Landmark', 'Banquet Halls', 'Liquor License'],
    highlights: [
      '12-year-old landmark heritage dining property',
      '3 private banquet halls — corporate and wedding bookings',
      'Advance bookings for next 4 months already confirmed',
      'Monthly revenue ₹12L–18L with 16% margin',
    ],
    heroImage: '/images/fine-dining-restaurant.jpg',
    publicImages: ['/images/fine-dining-restaurant.jpg'],
    fullAddress: 'Charminar Road, Ghansi Bazaar, Old City, Hyderabad - 500002',
    ownerName: 'Nawab Salim Khan',
    ownerPhone: '+91 98765 55555',
    ownerEmail: 'nawab@nawabsdarbar.com',
    exactMonthlyRevenue: 1500000,
    exactAskingPrice: 40000000,
    leaseYears: 8,
    profitMargin: 16,
    additionalNotes: 'Family-owned legacy property. Owner retiring. Staff of 45 to be retained.',
    fullGallery: ['/images/fine-dining-restaurant.jpg'],
  },
  {
    exactBusinessName: 'The Grand Pavilion',
    status: 'ACTIVE' as const,
    businessType: 'Luxury Hotel Restaurant',
    category: 'Restaurant',
    neighbourhood: 'Begumpet',
    revenueRangeMin: 2000000,
    revenueRangeMax: 3000000,
    askingPriceRangeMin: 60000000,
    askingPriceRangeMax: 80000000,
    yearsInOperation: 9,
    sqftRange: '8,000–10,000 sq ft',
    tags: ['5-Star Property', 'Banquets', 'Corporate Events', 'Premium Location'],
    highlights: [
      'Attached to a boutique hotel in Begumpet',
      'Corporate event and wedding revenue contributes 40% of income',
      'International cuisine menu curated by Executive Chef',
      'Monthly revenue ₹20L–30L with 18% margin',
    ],
    heroImage: '/images/luxury-hotel-restaurant.jpg',
    publicImages: ['/images/luxury-hotel-restaurant.jpg'],
    fullAddress: '6-3-249, Raj Bhavan Road, Begumpet, Hyderabad - 500016',
    ownerName: 'Rajesh Singhania',
    ownerPhone: '+91 98765 66666',
    ownerEmail: 'rajesh@grandpavilion.in',
    exactMonthlyRevenue: 2500000,
    exactAskingPrice: 70000000,
    leaseYears: 10,
    profitMargin: 18,
    additionalNotes: 'Hotel partnership agreement transferable. Full management team retained.',
    fullGallery: ['/images/luxury-hotel-restaurant.jpg'],
  },
  {
    exactBusinessName: 'The Copper Vat',
    status: 'ACTIVE' as const,
    businessType: 'Brewery & Gastropub',
    category: 'Restaurant',
    neighbourhood: 'Kondapur',
    revenueRangeMin: 1500000,
    revenueRangeMax: 2000000,
    askingPriceRangeMin: 40000000,
    askingPriceRangeMax: 55000000,
    yearsInOperation: 5,
    sqftRange: '7,000–8,000 sq ft',
    tags: ['Microbrewery', 'Liquor License', 'Live Music', '200+ Covers'],
    highlights: [
      'Fully operational microbrewery with 6 house beers on tap',
      'Live music every Friday and Saturday',
      'Average weekend footfall: 350–400 covers',
      'Monthly revenue ₹15L–20L with 22% margin',
    ],
    heroImage: '/images/restaurant-industrial.png',
    publicImages: ['/images/restaurant-industrial.png'],
    fullAddress: 'Plot 89, Kondapur Main Road, Kondapur, Hyderabad - 500084',
    ownerName: 'Karan Malhotra',
    ownerPhone: '+91 98765 88888',
    ownerEmail: 'karan@coppervat.in',
    exactMonthlyRevenue: 1750000,
    exactAskingPrice: 47000000,
    leaseYears: 7,
    profitMargin: 22,
    additionalNotes: 'Head brewer willing to stay on for 12 months. Brand fully transferable.',
    fullGallery: ['/images/restaurant-industrial.png'],
  },
]

async function main() {
  const existingNames = new Set(
    (await prisma.listing.findMany({ select: { exactBusinessName: true } }))
      .map((l: any) => l.exactBusinessName)
  )

  for (const data of seedData) {
    if (existingNames.has(data.exactBusinessName)) {
      console.log(`– Skipped: ${data.exactBusinessName} (already exists)`)
    } else {
      await prisma.listing.create({ data })
      console.log(`✓ Seeded: ${data.exactBusinessName}`)
    }
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
